name: Deploy to GitHub Pages

on:
  # Triggers the workflow automatically whenever you push code to your main branch
  push:
    branches: ["main"]

  # Allows you to manually trigger this workflow from the GitHub Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures that only one concurrent deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/pages-github-pages-config-action@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Uploads the entire root directory (where your index.html is located)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
